apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::137675731821:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JPBWNE0JEG2G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters  
      rolearn: arn:aws:iam::137675731821:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-27T11:01:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "895"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2f5cd530-6f55-4129-8276-4bc59fe79f0b
